---
# handlers file for ansible-role-filebeat-postfix-bounce
- name: restart filebeat
  service: 
    name: filebeat
    state: restarted

- name: enable filebeat
  service:
    name: filebeat
    enabled: yes
